In [79]:
# 사용할 라이브러리 임포트
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import plot_tree
from sklearn.linear_model import LinearRegression


In [39]:
df = sns.load_dataset('mpg')
df


mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  
0            70     usa  chevrolet chevelle malibu  
1            70     usa          buick skylark 320  
2            70     usa         plymouth satellite  
3            70     usa              amc rebel sst  
4            70     usa                ford torino  
..          ...     ...                        ...  
393          82     usa            ford mustang gl  
394          82  europe                  vw pickup  
395          82     usa              dodge rampage  
396          82     usa                ford ranger  
397          82     usa                 chevy s-10  

[398 rows x 9 columns]

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    object 
 8   name          398 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB


In [41]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mean())

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    object 
 8   name          398 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB


In [43]:
df.describe()

mpg   cylinders  displacement  horsepower       weight  \
count  398.000000  398.000000    398.000000  398.000000   398.000000   
mean    23.514573    5.454774    193.425879  104.469388  2970.424623   
std      7.815984    1.701004    104.269838   38.199187   846.841774   
min      9.000000    3.000000     68.000000   46.000000  1613.000000   
25%     17.500000    4.000000    104.250000   76.000000  2223.750000   
50%     23.000000    4.000000    148.500000   95.000000  2803.500000   
75%     29.000000    8.000000    262.000000  125.000000  3608.000000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration  model_year  
count    398.000000  398.000000  
mean      15.568090   76.010050  
std        2.757689    3.697627  
min        8.000000   70.000000  
25%       13.825000   73.000000  
50%       15.500000   76.000000  
75%       17.175000   79.000000  
max       24.800000   82.000000

In [70]:
X = df[['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year']]
y = df['mpg'].to_numpy()

In [71]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [72]:
X_train.shape, X_test.shape

((318, 6), (80, 6))

### 데이터 전처리

In [73]:
ss = StandardScaler()
ss.fit(X_train)

X_train_scaled = ss.transform(X_train)
X_test_scaled = ss.transform(X_test)

In [74]:
X_train_scaled

array([[ 1.52718818,  1.0901965 ,  1.26183446,  0.55282624, -1.31933367,
        -1.6966673 ],
       [-0.85051483, -0.92299623, -0.41351298, -0.99966729, -0.41318225,
        -1.6966673 ],
       [-0.85051483, -0.98134964, -0.95394763, -1.1247723 ,  0.92792185,
         1.63897537],
       ...,
       [-0.85051483, -0.56315019, -0.22436085, -0.54094894, -0.30444408,
         0.52709448],
       [-0.85051483, -1.00080078, -1.11607803, -1.09498539,  0.60170734,
         1.36100515],
       [-0.85051483, -0.92299623, -1.54842576, -1.21413301,  1.94281144,
        -0.86275663]])

In [75]:
X_test_scaled

array([[-0.85051483, -0.98134964, -1.35927363, -1.39881183,  0.63795339,
        -0.02884597],
       [-0.85051483, -0.69930815, -0.65670857, -0.40988656,  1.07290607,
         1.63897537],
       [ 0.33833667,  0.38995555, -0.08925218, -0.39916327, -0.9568731 ,
        -1.41869708],
       [ 1.52718818,  1.22635446,  1.26183446,  1.15690469, -0.88438099,
        -0.02884597],
       [ 1.52718818,  1.22635446,  1.26183446,  1.51077313, -0.41318225,
        -0.86275663],
       [-0.85051483, -0.92299623, -0.41351298, -1.03541158,  0.31173888,
        -1.14072686],
       [-0.85051483, -0.50479678, -0.30542605, -0.12393226,  0.27549283,
         1.63897537],
       [ 1.52718818,  2.41287384,  3.01824709,  2.10412829, -1.68179423,
        -0.86275663],
       [ 1.52718818,  0.66227147,  0.18096514,  1.29988184,  1.2178903 ,
         0.24912426],
       [ 0.33833667,  0.07873735,  0.03151842, -0.1120175 ,  0.49296917,
        -0.58478641],
       [ 1.52718818,  1.92659541,  2.34270377,  1.

In [76]:
y_test, y_train

(array([33. , 28. , 19. , 13. , 14. , 27. , 24. , 13. , 17. , 21. , 15. ,
        38. , 26. , 15. , 25. , 12. , 31. , 17. , 16. , 31. , 22. , 22. ,
        22. , 33.5, 18. , 44. , 26. , 24.5, 18.1, 12. , 27. , 36. , 23. ,
        24. , 37.2, 16. , 21. , 19.2, 16. , 29. , 26.8, 27. , 18. , 10. ,
        23. , 36. , 26. , 25. , 25. , 25. , 22. , 34.1, 32.4, 13. , 23.5,
        14. , 18.5, 29.8, 28. , 19. , 11. , 33. , 23. , 21. , 23. , 25. ,
        23.8, 34.4, 24.5, 13. , 34.7, 14. , 15. , 18. , 25. , 19.9, 17.5,
        28. , 29. , 17. ]),
 array([16. , 27. , 37. , 36.1, 23. , 14. , 32.8, 29.9, 20. , 12. , 15.5,
        23.7, 24. , 36. , 19. , 38. , 29. , 21.5, 27.9, 14. , 36.1, 22. ,
        18. , 17. , 18. , 14. , 26. , 13. , 33. , 37. , 32. , 28. , 19.2,
        32. , 27.4, 20. , 26. , 20.6, 37.3, 16.2, 15. , 21. , 21. , 20.5,
        21. , 25.4, 34.1, 27. , 36. , 31.6, 38.1, 32. , 40.8, 19. , 20. ,
        22. , 17.5, 35.1, 30.5, 33.7, 19. , 14. , 15.5, 15. , 22.5, 29. ,
        23

In [81]:
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [83]:
print(lr.predict(X_test))

[31.53109579 30.70849255 21.76226    17.00367581 12.6130019  26.21298858
 28.91110402  9.203019   17.21958478 22.74890141 12.68127025 34.98788977
 26.69305024 14.05845246 24.77721826  5.90349606 30.87237625 23.812746
 15.88074362 35.1630653  23.44503249 19.69097766 29.32850815 30.33475799
 15.09790363 34.56140773 25.77970744 25.76026735 22.17155643  7.92248019
 29.35879131 34.94809283 20.00733969 24.92500913 33.10362116 12.27718714
 24.47963851 22.19709231 12.37774229 26.9653782  27.64455572 27.40742955
 20.29321008  7.75458288 23.2567278  33.67959269 26.58280382 24.46965565
 22.78493184 27.69250537 23.46866786 32.51641698 31.29673875 10.59203038
 29.0331764   9.37415973 19.459108   28.30596417 24.25237835 20.74590348
 16.50177291 30.73792699 24.91739479 20.29843339 21.63449641 24.35609011
 25.87130899 33.72516256 29.33902158 12.67787803 32.43029722 13.33055945
  9.42921327 19.56240271 28.60182876 22.6343755  20.65938631 30.94091434
 29.50369472 20.21097656]


In [84]:
print(lr.coef_, lr.intercept_)

[ 0.06912753  0.00161762  0.00274372 -0.00704049  0.07985934  0.80115473] -18.677658874713345


In [87]:
print(lr.score(X_train, y_train))
print(lr.score(X_test, y_test))

0.8038965489657075
0.8244069426990221


In [88]:
X_train ** 2, X_train

(     cylinders  displacement  horsepower    weight  acceleration  model_year
 3           64       92416.0     22500.0  11785489        144.00        4900
 18          16        9409.0      7744.0   4536900        210.25        4900
 376         16        8281.0      4624.0   4100625        331.24        6724
 248         16        8281.0      3600.0   3240000        268.96        6084
 177         16       13225.0      9025.0   7257636        225.00        5625
 ..         ...           ...         ...       ...           ...         ...
 71           9        4900.0      9409.0   5428900        182.25        5184
 106         64      122500.0     32400.0  20241001        156.25        5329
 270         16       17956.0      9025.0   6325225        219.04        6084
 348         16        7921.0      3844.0   4202500        299.29        6561
 102         16        9409.0      2116.0   3802500        441.00        5329
 
 [318 rows x 6 columns],
      cylinders  displacement  horsep

In [77]:
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train_scaled, y_train)

print(dt.score(X_train_scaled, y_train))
print(dt.score(X_test_scaled, y_test))

ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.